# Generated by Django 4.2.7 on 2025-04-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='businesses',
            field=models.ManyToManyField(related_name='delivery_zones', to='accounts.businessprofile'),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='city',
            field=models.CharField(default='Default City', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='assigned', max_length=20),
        ),
    ]
