# Generated by Django 4.2.7 on 2025-04-13 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderpayment_delete_payment'),
        ('accounts', '0002_rename_business_description_businessprofile_description_and_more'),
        ('delivery', '0003_delivery_remove_deliveryrating_assignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='deliverytracking',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='actual_delivery_time',
            new_name='delivered_at',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='actual_pickup_time',
            new_name='picked_up_at',
        ),
        migrations.RenameField(
            model_name='deliverytracking',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='pickup_time',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='deliverytracking',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='deliverytracking',
            name='location',
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='deliverytracking',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='accounts.riderprofile'),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='delivery.delivery'),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverytracking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=50),
        ),
    ]
