# Generated by Django 4.2.7 on 2025-04-12 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessprofile',
            old_name='business_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_email',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_phone',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_website',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='preferred_payment_method',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='riderprofile',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('grocery', 'Grocery Store'), ('pharmacy', 'Pharmacy'), ('retail', 'Retail Store'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('bicycle', 'Bicycle'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('scooter', 'Scooter')], max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(help_text='e.g., Home, Office', max_length=50)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
